/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-07 15:29:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Merriweather&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"module\" src=\"Validations/ValidationRegister.mjs\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tbackground: #464c80;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\tfont-size: 62.5%; /* This is equivalent to 10px */\r\n");
      out.write("\t\tfont-family: 'Merriweather', serif;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdiv.main-container-div {\r\n");
      out.write("\t\theight: 150%;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\tjustify-content: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdiv.form-container-div {\r\n");
      out.write("\t\tmargin: 100px;\r\n");
      out.write("\t\tborder-radius: 6px;\r\n");
      out.write("\t\tbackground: #fff;\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t\tbox-shadow: 1px 1px 25px 1px #000; \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdiv.form-container-div form {\r\n");
      out.write("\t\tpadding: 10px 30px 30px 30px;\r\n");
      out.write("\t\tfont-size: 1.6em;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv.form-container-div .register-div {\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tborder-radius: 5px 5px 0 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdiv.form-container-div .register-div h1 {\r\n");
      out.write("\t\tfont-size: 3.5em;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Inside form-container-div */\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div {\r\n");
      out.write("\t\tpadding: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div {\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\tjustify-content: space-between;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div .form-input {\r\n");
      out.write("\t\twidth: 63%;\r\n");
      out.write("\t\theight: 20px;\r\n");
      out.write("\t\tfont-family: inherit;\r\n");
      out.write("\t\tfont-size: .8em;\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t\tborder: 1px solid #464c80;\r\n");
      out.write("\t\tpadding: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div div[class$=\"wrong-validation-div\"] {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\tjustify-content: flex-end;\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\topacity: 0;\r\n");
      out.write("\t\ttransition: opacity .5s linear;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div div[class$=\"wrong-validation-div\"] p {\r\n");
      out.write("\t\twidth: 63%;\r\n");
      out.write("\t\tpadding: 5px;\r\n");
      out.write("\t\tfont-size: .7em;\r\n");
      out.write("\t\tborder: 1px solid #e21010;\r\n");
      out.write("\t\tcolor: #e21010;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div label {\r\n");
      out.write("\t\theight: 20px;\r\n");
      out.write("\t\tpadding: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div .submit-btn {\r\n");
      out.write("\t\tfont-family: inherit;\r\n");
      out.write("\t\tfont-size: .8em;\r\n");
      out.write("\t\tmargin: 15px auto 5px auto;\r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t\tpadding: 5px;\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\tbackground: #464c80;\r\n");
      out.write("\t\tborder-radius: 20px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\ttransition: background-color .3s linear;\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .login-back-link-div {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .login-back-link-div span {\r\n");
      out.write("\t\tcolor: #464c80;\r\n");
      out.write("\t\tfont-size: 0.75em;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.inputs-group-div .login-back-link-div span a {\r\n");
      out.write("\t\tcolor: #464c80;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Buttons, boxes and links interactions */\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div .submit-btn:hover {\r\n");
      out.write("\t\tbackground:#666dad;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div .submit-btn:active {\r\n");
      out.write("\t\tbackground: #272b50;\r\n");
      out.write("\t\ttransition: none;\r\n");
      out.write("\t\tborder: 1.5px solid #bfc4fd;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputs-group-div .input-div .form-input:focus {\r\n");
      out.write("\t\tbackground: #d1d8f1;\r\n");
      out.write("\t\tborder: 1px solid #000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.inputs-group-div .form-input:-internal-autofill-selected {\r\n");
      out.write("\t\tbackground-color: #d1d8f1 !important;\r\n");
      out.write("\t\tborder: 1px solid #000 !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.inputs-group-div .input-div .submit-btn:focus {\r\n");
      out.write("\t\tbackground: #272b50;\r\n");
      out.write("\t\ttransition: none;\r\n");
      out.write("\t\tborder: 1.5px solid #bfc4fd;\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("\t.inputs-group-div .login-back-link-div span a:visited,\r\n");
      out.write("\t.inputs-group-div .login-back-link-div span a:active {\r\n");
      out.write("\t\tcolor: inherit;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main container -->\r\n");
      out.write("\t<div class=\"main-container-div\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-container-div\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- Register div -->\r\n");
      out.write("\t\t\t<div class=\"register-div\">\r\n");
      out.write("\t\t\t\t<h1>Register</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Form -->\r\n");
      out.write("\t\t\t<form name=\"registerForm\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"inputs-group-div\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"name\">Name</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"text\" name=\"name\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"name-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"name-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"surname\">Surname</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"text\" name=\"surname\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"surname-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"surname-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"username\">Username</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"text\" name=\"username\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"username-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"username-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"phone\">Phone</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"text\" name=\"phone\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"phone-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"phone-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"email\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"text\" name=\"email\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"email-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"email-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"password\" name=\"password\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"password-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"password-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Input item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"confirm\">Confirm</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-input\" type=\"password\" name=\"confirm\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Error item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"confirm-wrong-validation-div\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"confirm-wrong-validation\"><span></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"input-div\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"submit-btn\" type=\"submit\" value=\"Register\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"login-back-link-div\">\r\n");
      out.write("\t\t\t\t\t\t<span><a href=\"./index.jsp\">Back to login</a></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
